---
- hosts: LAB
  gather_facts: no
  become: yes

  # do the preparation
  pre_tasks:
    # - name: ping test to verify destiation status
    #   command: timeout 0.3 ping -c 1 {{ inventory_hostname }}
    #   delegate_to: localhost
    #   register: ping
    #   failed_when: ping.rc != 0
    #   changed_when: False
    #   tags: always

    - debug:  msg="You are acting the {{ inventory_hostname }} , ansible_host {{ ansible_host }} "
      tags: always

    - name: Exterminate mankind
      pause: prompt='Please confirm you want to exterminate mankind! Press return to continue. Press Ctrl+c and then "a" to abort'
      tags: always


    - name: Load list specific users of cluster 
      include_vars: "{{ playbook_dir }}/include.d/root_per_users.yaml"
      tags: [user, ssh, root_permission]

    - name: Gathering facts
      setup:
      tags: always

###-----ROLES----###
  roles:

  # Tag tạo root permission user
  - role: "user/root_permission"
    tags: [root_permission]


  environment:
    http_proxy: '{{http_proxy}}'
    https_proxy: '{{https_proxy}}'

